name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # main 分支有 push 时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: 20 # 使用合适的Node版本，根据你的项目需求
      - run: npm install
      - run: npm run build

      # - name: Set up Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: 20 # 使用合适的Node版本，根据你的项目需求

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          publish_dir: ./dist  # 指定发布目录为dist目录
          github_token: ${{ secrets.ACL_DEMO }} # 自动提供的token，用于认证推送操作
          # user_name: ${{ secrets.MY_USER_NAME }}
          # user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: "自动部署"
