/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'home': RouteRecordInfo<'home', '/', Record<never, never>, Record<never, never>>,
    // '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/agreement/infoAgreement': RouteRecordInfo<'/agreement/infoAgreement', '/agreement/infoAgreement', Record<never, never>, Record<never, never>>,
    '/agreement/serviceAgreement': RouteRecordInfo<'/agreement/serviceAgreement', '/agreement/serviceAgreement', Record<never, never>, Record<never, never>>,
    'charts': RouteRecordInfo<'charts', '/charts', Record<never, never>, Record<never, never>>,
    'counter': RouteRecordInfo<'counter', '/counter', Record<never, never>, Record<never, never>>,
    'create': RouteRecordInfo<'create', '/create', Record<never, never>, Record<never, never>>,
    'success': RouteRecordInfo<'success', '/create/success', Record<never, never>, Record<never, never>>,
    'demo': RouteRecordInfo<'demo', '/demo', Record<never, never>, Record<never, never>>,
    'awarding': RouteRecordInfo<'awarding', '/explain/awarding', Record<never, never>, Record<never, never>>,
    'illustration': RouteRecordInfo<'illustration', '/explain/illustration', Record<never, never>, Record<never, never>>,
    'homeIndex': RouteRecordInfo<'homeIndex', '/home/homeIndex', Record<never, never>, Record<never, never>>,
    'homecopy': RouteRecordInfo<'homecopy', '/index copy', Record<never, never>, Record<never, never>>,
    'KeepAlive': RouteRecordInfo<'KeepAlive', '/keepalive', Record<never, never>, Record<never, never>>,
    'mock': RouteRecordInfo<'mock', '/mock', Record<never, never>, Record<never, never>>,
    'details': RouteRecordInfo<'details', '/product/details', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'query': RouteRecordInfo<'query', '/query', Record<never, never>, Record<never, never>>,
    'progress': RouteRecordInfo<'progress', '/query/progress', Record<never, never>, Record<never, never>>,
    'fail': RouteRecordInfo<'fail', '/result/fail', Record<never, never>, Record<never, never>>,
    'unocss': RouteRecordInfo<'unocss', '/unocss', Record<never, never>, Record<never, never>>,
  }
}
